# BiocManager::install("MotifDb")
library(MotifDb)
MotifDb

pckgs = c("bigWig","rphast","rtfbs","cluster",
          "latticeExtra",'lattice',"apcluster",
          "vioplot","RCurl","parallel")
find.package(pckgs)
find.package("bigWig")
install.packages("bigWig")
install.packages("rphast")
install.packages("rtfbs")
install.packages("apcluster")
install.packages("vioplot")
install.packages("RCurl")

####
library(rtfbsdb)
#db <- CisBP.download("Bos_taurus")

db<- CisBP.zipload("Bos_taurus_2020_02_27_4_01_pm.zip", species="Bos_taurus")
db <- CisBP.download("Bos_taurus")
tfs <- tfbs.createFromCisBP(db)
show(tfs)

# Load the subset of MotifDb generated by the method in 
# 'MotifDb' package
library(MotifDb);
bta.human <- query(MotifDb, 'hsapiens');
tfs1 <- tfbs.createFromMotifDb(mdb.human, organism=NULL);
